[package]
name = "arch-lint"
version = "0.1.0"
edition = "2021"

[dependencies]
owo-colors = { version = "4", features = ["supports-colors"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"
