[package]
name = "dev-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "brad-validate"
path = "src/bin/validate.rs"

[[bin]]
name = "brad-run-integration-tests"
path = "src/bin/run-integration-tests.rs"

[dependencies]
owo-colors = { version = "4", features = ["supports-colors"] }
ctrlc = "3.4.4"

[dev-dependencies]
tempfile = "3"
